### ISSUE TITLE
tests hang when compiled with GCC 5 series

### ISSUE THREAD

**Issue by keisukefukuda** [massivethreads/massivethreads#2]
make check hangs when compiled with gcc 5 series.

Compilers : gcc 5.1, gcc 5.2 (custom builds)

When `MYTH_NUM_WORKER=1`, tests proceed to `myth_create_2`, but hangs on `myth_create_join`

Changing optimisation flag to `-O0` in `configure.ac`, all tests pass.

By using gdb, `myth_create_0` test seem to loop over the two points.

    0x00007f12c3b20db9 in calloc (nmemb=2400, size=1) at myth_malloc_wrapper.c:235
    235       if (!g_wrap_malloc_completed) {

    0x00007f12c3b20dc4 in calloc (nmemb=2400, size=1) at myth_malloc_wrapper.c:241
    241       if (!g_wrap_malloc) {

When compiled with `./configure --enable-malloc-wrapper=no`, all tests pass.

**Comment by taura** [comment]
fixed with commit 298d2a89ca68774a6faa87b56b671d5bfcee2609

wrapped calloc used to call wrapped malloc. essentially,
calloc(n, sz) {
   ... malloc(n * sz);  // intend to call wrapped malloc
}
With gcc 5.x, the call to malloc somehow jumps to calloc@plt, which arrives at the
wrapped calloc, leading to an infinite loop.

(I tried to make a minimum working example for this but so far couldn't)

I fixed it by 
(1) defining myth_malloc_wrapper_malloc 
(2) both malloc and calloc now call myth_malloc_wrapper_malloc

I did similar things for other wrapped functions (posix_memalign etc.),
so that the library never calls  functions supposed to be wrapped.
